print("TIPOS DE DATOS")
print(type(1.3746))
print(type(-23))
print(type(True))
print(type(12))
print(type(0j))
print(type(13.14))
print(type)
variable= ("abcdefghijk")
#Los espacios tambien representan un elemento en una cadena de 
#de caracteres
print(f"sintaxis basica para ingresar a una variable [inicio:fin:salto ]")
print(f"sintaxis basica para el indice en una cadena ['a b c d e f g h i j k' ]")
print(f"sintaxis basica para el indice en una indice ['0.1.2.3.4.5.6.7.8.9.10' ]")
print(f"'variable':{variable}")
print(f"variable[0:5]{variable[0:5]}")
print(f"variable[:2:]{variable[:2:]}")
print(f"variable[: :8]{variable[: :8]}")
print("sintaxis basica para ingresar a una variable [inicio:fin:salto ]")
print("sintaxis basica para el indice en una cadena - [' a  b  c  d  e  f  g  h  i  j  k' ]")
print("sintaxis basica para el indice en un  indice - ['-10.-9.-8.-7.-6.-5.-4.-3.-2.-1.0' ]")
print(f"'variable':{variable}")
print(f"variable[0:-5]{variable[0:-5]}")
print(f"variable[:-10:]{variable[:-10:]}")
print(f"variable[: :-8]{variable[: :-3]}")
method=("python")
print(f"Ejemplificando metodos en: {method}= variable inicial")
print(f"Ejemplificando metodos en: {method.capitalize()}= variable con metodo capitalize")
print(f"Ejemplificando metodos en: {method.lower()}= variable con metodo .lower()")
print(f"Ejemplificando metodos en: {method.lstrip()}= variable con metodo(formato) .lstrip()")
print(f"Ejemplificando metodos en: {method.rstrip()}= variable con metodo(formato) .rstrip()")
print(f"Ejemplificando metodos en: {method.replace('e', 'a')}= variable con metodo .replace('e', 'a')")
print(f"Ejemplificando metodos en: {method.split('c')}= variable con metodo .split('c')")
print(f"Ejemplificando metodos en: {method.swapcase()}= variable con metodo .swapcase()")
print(f"Ejemplificando metodos en: {method.title()}= variable con metodo .title()")
print(f"Ejemplificando metodos en: {method.upper()}= variable con metodo .upper()")
print("METODOS CON RESPUESTA BOLEAN")
method_bolean=("JORGE TE AMO")
print(f"Mi variable:{method_bolean}")
print(f"Mi variable con el metodo .isalnum(){method_bolean.isalnum()}")
print(f"Mi variable con el metodo .isalpha(): {method_bolean.isalpha()}")
print(f"Mi variable con el metodo .isdecimal():{method_bolean.isdecimal()}")
print(f"Mi variable con el metodo .isdigit:{method_bolean.isdigit()}")
print(f"Mi variable con el metodo .isidentifier():{method_bolean.isidentifier()}")
print(f"Mi variable con el metodo .islower(): {method_bolean.islower()}")
print(f"Mi variable con el metodo .isnumeric():{method_bolean.isnumeric()}")
print(f"Mi variable con el metodo .isprintable():{method_bolean.isprintable()}")
print(f"Mi variable con el metodo .isspace():{method_bolean.isspace()}")
print(f"Mi variable con el metodo .istitle:{method_bolean.istitle()}")
print(f"Mi variable con el metodo .isupper: {method_bolean.isupper()}")
print("METODOS CON RESPUESTA INT")
method_int=("ONE")
print(f"Mi variable con el metodo .count('C'): {method_int.count('C')}")
print(f"Mi variable con el metodo .find('e'): {method_int.find('e')}")
print(f"Mi variable con el metodo .index('p'): {method_int.index('p')}")


